import {
  LayoutDashboard,
  Building2,
  Users,
  Briefcase,
  FileText,
  Bell,
  Settings,
  User,
  LogOut,
  Search,
  Plus,
  Filter,
  ChevronDown,
  ChevronRight,
  Menu,
  X,
  Home,
  BarChart3,
  TrendingUp,
  DollarSign,
  Shield,
  Star,
  Award,
  Target,
  Rocket,
  Activity,
  Mail,
  Phone,
  Calendar,
  Upload,
  Download,
  Edit,
  Trash2,
  Eye,
  Clock,
  Check,
  AlertTriangle,
  Info,
  Globe,
  MapPin,
  Inbox,
  FolderOpen,
  ClipboardList,
  Handshake,
  UserCircle,
  MessageSquare,
  ShieldCheck,
  TrendingDown,
  CheckCircle2,
  Clock3,
  Lock,
  FileCheck,
LockKeyhole,
Bookmark,
AlertCircle,
EyeOff,
Send,
Sparkles,
 ChevronLeft


} from "lucide-react";
export const Icons = {
  dashboard: LayoutDashboard,
  listings: Building2,
  users: Users,
  briefcase: Briefcase,
  file: FileText,
  bell: Bell,
  settings: Settings,
  user: User,
  logout: LogOut,
  search: Search,
  plus: Plus,
  filter: Filter,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  menu: Menu,
  close: X,
  home: Home,
  chart: BarChart3,
  trending: TrendingUp,
  money: DollarSign,
  shield: Shield,
  star: Star,
  award: Award,
  target: Target,
  rocket: Rocket,
  activity: Activity,
  mail: Mail,
  phone: Phone,
  calendar: Calendar,
  upload: Upload,
  download: Download,
  edit: Edit,
  trash: Trash2,
  eye: Eye,
  clock: Clock,
  check: Check,
  warning: AlertTriangle,
  alert: AlertTriangle,
  info: Info,
  globe: Globe,
  location: MapPin,
  inbox: Inbox,

  // aliases used in DashboardLayout
  documents: FileText,
  updates: Activity,
  scores: BarChart3,
  logs: Eye,
  pipeline: Briefcase,
  profile: User,
  discover: Search,
  saved: Star,
  interests: Inbox
};